---

- name: Collect commands
  hosts: DC1_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd

  tasks:
    - name: Collect show commands and generate reports
      import_role:
        name: arista.avd.eos_snapshot